from typing import Dict, List, Tuple, Optional
import re

"""
FIPS County Search Tool

This module provides a keyword search function to find county FIPS codes.
It searches through county names and returns matching results with their FIPS codes.
This is designed for use as an LLM tool to provide manageable result sets.
"""

def _get_county_fips_data() -> Dict[str, str]:
    """Internal function containing the complete county FIPS dictionary."""
    return {
        "Ada County, Idaho": "001",
        "Adair County, Iowa": "001",
        "Adams County, Colorado": "001",
        "Adams County, Idaho": "003",
        "Adams County, Illinois": "001",
        "Adams County, Indiana": "001",
        "Adams County, Iowa": "003",
        "Alachua County, Florida": "001",
        "Alameda County, California": "001",
        "Alamosa County, Colorado": "003",
        "Aleutians East Borough, Alaska": "013",
        "Aleutians West Census Area, Alaska": "016",
        "Alexander County, Illinois": "003",
        "Allamakee County, Iowa": "005",
        "Allen County, Indiana": "003",
        "Allen County, Kansas": "001",
        "Alpine County, California": "003",
        "Amador County, California": "005",
        "Anchorage Municipality, Alaska": "020",
        "Anderson County, Kansas": "003",
        "Apache County, Arizona": "001",
        "Appanoose County, Iowa": "007",
        "Appling County, Georgia": "001",
        "Arapahoe County, Colorado": "005",
        "Archuleta County, Colorado": "007",
        "Arkansas County, Arkansas": "001",
        "Ashley County, Arkansas": "003",
        "Atchison County, Kansas": "005",
        "Atkinson County, Georgia": "003",
        "Audubon County, Iowa": "009",
        "Autauga County, Alabama": "001",
        "Baca County, Colorado": "009",
        "Bacon County, Georgia": "005",
        "Baker County, Florida": "003",
        "Baker County, Georgia": "007",
        "Baldwin County, Alabama": "003",
        "Baldwin County, Georgia": "009",
        "Banks County, Georgia": "011",
        "Bannock County, Idaho": "005",
        "Barber County, Kansas": "007",
        "Barbour County, Alabama": "005",
        "Barrow County, Georgia": "013",
        "Bartholomew County, Indiana": "005",
        "Barton County, Kansas": "009",
        "Bartow County, Georgia": "015",
        "Baxter County, Arkansas": "005",
        "Bay County, Florida": "005",
        "Bear Lake County, Idaho": "007",
        "Ben Hill County, Georgia": "017",
        "Benewah County, Idaho": "009",
        "Bent County, Colorado": "011",
        "Benton County, Arkansas": "007",
        "Benton County, Indiana": "007",
        "Benton County, Iowa": "011",
        "Berrien County, Georgia": "019",
        "Bethel Census Area, Alaska": "050",
        "Bibb County, Alabama": "007",
        "Bibb County, Georgia": "021",
        "Bingham County, Idaho": "011",
        "Black Hawk County, Iowa": "013",
        "Blackford County, Indiana": "009",
        "Blaine County, Idaho": "013",
        "Bleckley County, Georgia": "023",
        "Blount County, Alabama": "009",
        "Boise County, Idaho": "015",
        "Bond County, Illinois": "005",
        "Bonner County, Idaho": "017",
        "Bonneville County, Idaho": "019",
        "Boone County, Arkansas": "009",
        "Boone County, Illinois": "007",
        "Boone County, Indiana": "011",
        "Boone County, Iowa": "015",
        "Boulder County, Colorado": "013",
        "Boundary County, Idaho": "021",
        "Bourbon County, Kansas": "011",
        "Bradford County, Florida": "007",
        "Bradley County, Arkansas": "011",
        "Brantley County, Georgia": "025",
        "Bremer County, Iowa": "017",
        "Brevard County, Florida": "009",
        "Bristol Bay Borough, Alaska": "060",
        "Brooks County, Georgia": "027",
        "Broomfield County, Colorado": "014",
        "Broward County, Florida": "011",
        "Brown County, Illinois": "009",
        "Brown County, Indiana": "013",
        "Brown County, Kansas": "013",
        "Bryan County, Georgia": "029",
        "Buchanan County, Iowa": "019",
        "Buena Vista County, Iowa": "021",
        "Bulloch County, Georgia": "031",
        "Bullock County, Alabama": "011",
        "Bureau County, Illinois": "011",
        "Burke County, Georgia": "033",
        "Butler County, Alabama": "013",
        "Butler County, Iowa": "023",
        "Butler County, Kansas": "015",
        "Butte County, California": "007",
        "Butte County, Idaho": "023",
        "Butts County, Georgia": "035",
        "Calaveras County, California": "009",
        "Calhoun County, Alabama": "015",
        "Calhoun County, Arkansas": "013",
        "Calhoun County, Florida": "013",
        "Calhoun County, Georgia": "037",
        "Calhoun County, Illinois": "013",
        "Calhoun County, Iowa": "025",
        "Camas County, Idaho": "025",
        "Camden County, Georgia": "039",
        "Candler County, Georgia": "043",
        "Canyon County, Idaho": "027",
        "Capitol Planning Region, Connecticut": "110",
        "Caribou County, Idaho": "029",
        "Carroll County, Arkansas": "015",
        "Carroll County, Georgia": "045",
        "Carroll County, Illinois": "015",
        "Carroll County, Indiana": "015",
        "Carroll County, Iowa": "027",
        "Cass County, Illinois": "017",
        "Cass County, Indiana": "017",
        "Cass County, Iowa": "029",
        "Cassia County, Idaho": "031",
        "Catoosa County, Georgia": "047",
        "Cedar County, Iowa": "031",
        "Cerro Gordo County, Iowa": "033",
        "Chaffee County, Colorado": "015",
        "Chambers County, Alabama": "017",
        "Champaign County, Illinois": "019",
        "Charlotte County, Florida": "015",
        "Charlton County, Georgia": "049",
        "Chase County, Kansas": "017",
        "Chatham County, Georgia": "051",
        "Chattahoochee County, Georgia": "053",
        "Chattooga County, Georgia": "055",
        "Chautauqua County, Kansas": "019",
        "Cherokee County, Alabama": "019",
        "Cherokee County, Georgia": "057",
        "Cherokee County, Iowa": "035",
        "Cherokee County, Kansas": "021",
        "Cheyenne County, Colorado": "017",
        "Cheyenne County, Kansas": "023",
        "Chickasaw County, Iowa": "037",
        "Chicot County, Arkansas": "017",
        "Chilton County, Alabama": "021",
        "Choctaw County, Alabama": "023",
        "Christian County, Illinois": "021",
        "Chugach Census Area, Alaska": "063",
        "Citrus County, Florida": "017",
        "Clark County, Arkansas": "019",
        "Clark County, Idaho": "033",
        "Clark County, Illinois": "023",
        "Clark County, Indiana": "019",
        "Clark County, Kansas": "025",
        "Clarke County, Alabama": "025",
        "Clarke County, Georgia": "059",
        "Clarke County, Iowa": "039",
        "Clay County, Alabama": "027",
        "Clay County, Arkansas": "021",
        "Clay County, Florida": "019",
        "Clay County, Georgia": "061",
        "Clay County, Illinois": "025",
        "Clay County, Indiana": "021",
        "Clay County, Iowa": "041",
        "Clay County, Kansas": "027",
        "Clayton County, Georgia": "063",
        "Clayton County, Iowa": "043",
        "Clear Creek County, Colorado": "019",
        "Clearwater County, Idaho": "035",
        "Cleburne County, Alabama": "029",
        "Cleburne County, Arkansas": "023",
        "Cleveland County, Arkansas": "025",
        "Clinch County, Georgia": "065",
        "Clinton County, Illinois": "027",
        "Clinton County, Indiana": "023",
        "Clinton County, Iowa": "045",
        "Cloud County, Kansas": "029",
        "Cobb County, Georgia": "067",
        "Cochise County, Arizona": "003",
        "Coconino County, Arizona": "005",
        "Coffee County, Alabama": "031",
        "Coffee County, Georgia": "069",
        "Coffey County, Kansas": "031",
        "Colbert County, Alabama": "033",
        "Coles County, Illinois": "029",
        "Collier County, Florida": "021",
        "Colquitt County, Georgia": "071",
        "Columbia County, Arkansas": "027",
        "Columbia County, Florida": "023",
        "Columbia County, Georgia": "073",
        "Colusa County, California": "011",
        "Comanche County, Kansas": "033",
        "Conecuh County, Alabama": "035",
        "Conejos County, Colorado": "021",
        "Contra Costa County, California": "013",
        "Conway County, Arkansas": "029",
        "Cook County, Georgia": "075",
        "Cook County, Illinois": "031",
        "Coosa County, Alabama": "037",
        "Copper River Census Area, Alaska": "066",
        "Costilla County, Colorado": "023",
        "Covington County, Alabama": "039",
        "Coweta County, Georgia": "077",
        "Cowley County, Kansas": "035",
        "Craighead County, Arkansas": "031",
        "Crawford County, Arkansas": "033",
        "Crawford County, Georgia": "079",
        "Crawford County, Illinois": "033",
        "Crawford County, Indiana": "025",
        "Crawford County, Iowa": "047",
        "Crawford County, Kansas": "037",
        "Crenshaw County, Alabama": "041",
        "Crisp County, Georgia": "081",
        "Crittenden County, Arkansas": "035",
        "Cross County, Arkansas": "037",
        "Crowley County, Colorado": "025",
        "Cullman County, Alabama": "043",
        "Cumberland County, Illinois": "035",
        "Custer County, Colorado": "027",
        "Custer County, Idaho": "037",
        "Dade County, Georgia": "083",
        "Dale County, Alabama": "045",
        "Dallas County, Alabama": "047",
        "Dallas County, Arkansas": "039",
        "Dallas County, Iowa": "049",
        "Daviess County, Indiana": "027",
        "Davis County, Iowa": "051",
        "Dawson County, Georgia": "085",
        "De Witt County, Illinois": "039",
        "DeKalb County, Alabama": "049",
        "DeKalb County, Georgia": "089",
        "DeKalb County, Illinois": "037",
        "DeKalb County, Indiana": "033",
        "DeSoto County, Florida": "027",
        "Dearborn County, Indiana": "029",
        "Decatur County, Georgia": "087",
        "Decatur County, Indiana": "031",
        "Decatur County, Iowa": "053",
        "Decatur County, Kansas": "039",
        "Del Norte County, California": "015",
        "Delaware County, Indiana": "035",
        "Delaware County, Iowa": "055",
        "Delta County, Colorado": "029",
        "Denali Borough, Alaska": "068",
        "Denver County, Colorado": "031",
        "Des Moines County, Iowa": "057",
        "Desha County, Arkansas": "041",
        "Dickinson County, Iowa": "059",
        "Dickinson County, Kansas": "041",
        "Dillingham Census Area, Alaska": "070",
        "District of Columbia, District of Columbia": "001",
        "Dixie County, Florida": "029",
        "Dodge County, Georgia": "091",
        "Dolores County, Colorado": "033",
        "Doniphan County, Kansas": "043",
        "Dooly County, Georgia": "093",
        "Dougherty County, Georgia": "095",
        "Douglas County, Colorado": "035",
        "Douglas County, Georgia": "097",
        "Douglas County, Illinois": "041",
        "Douglas County, Kansas": "045",
        "Drew County, Arkansas": "043",
        "DuPage County, Illinois": "043",
        "Dubois County, Indiana": "037",
        "Dubuque County, Iowa": "061",
        "Duval County, Florida": "031",
        "Eagle County, Colorado": "037",
        "Early County, Georgia": "099",
        "Echols County, Georgia": "101",
        "Edgar County, Illinois": "045",
        "Edwards County, Illinois": "047",
        "Edwards County, Kansas": "047",
        "Effingham County, Georgia": "103",
        "Effingham County, Illinois": "049",
        "El Dorado County, California": "017",
        "El Paso County, Colorado": "041",
        "Elbert County, Colorado": "039",
        "Elbert County, Georgia": "105",
        "Elk County, Kansas": "049",
        "Elkhart County, Indiana": "039",
        "Ellis County, Kansas": "051",
        "Ellsworth County, Kansas": "053",
        "Elmore County, Alabama": "051",
        "Elmore County, Idaho": "039",
        "Emanuel County, Georgia": "107",
        "Emmet County, Iowa": "063",
        "Escambia County, Alabama": "053",
        "Escambia County, Florida": "033",
        "Etowah County, Alabama": "055",
        "Evans County, Georgia": "109",
        "Fairbanks North Star Borough, Alaska": "090",
        "Fannin County, Georgia": "111",
        "Faulkner County, Arkansas": "045",
        "Fayette County, Alabama": "057",
        "Fayette County, Georgia": "113",
        "Fayette County, Illinois": "051",
        "Fayette County, Indiana": "041",
        "Fayette County, Iowa": "065",
        "Finney County, Kansas": "055",
        "Flagler County, Florida": "035",
        "Floyd County, Georgia": "115",
        "Floyd County, Indiana": "043",
        "Floyd County, Iowa": "067",
        "Ford County, Illinois": "053",
        "Ford County, Kansas": "057",
        "Forsyth County, Georgia": "117",
        "Fountain County, Indiana": "045",
        "Franklin County, Alabama": "059",
        "Franklin County, Arkansas": "047",
        "Franklin County, Florida": "037",
        "Franklin County, Georgia": "119",
        "Franklin County, Idaho": "041",
        "Franklin County, Illinois": "055",
        "Franklin County, Indiana": "047",
        "Franklin County, Iowa": "069",
        "Franklin County, Kansas": "059",
        "Fremont County, Colorado": "043",
        "Fremont County, Idaho": "043",
        "Fremont County, Iowa": "071",
        "Fresno County, California": "019",
        "Fulton County, Arkansas": "049",
        "Fulton County, Georgia": "121",
        "Fulton County, Illinois": "057",
        "Fulton County, Indiana": "049",
        "Gadsden County, Florida": "039",
        "Gallatin County, Illinois": "059",
        "Garfield County, Colorado": "045",
        "Garland County, Arkansas": "051",
        "Geary County, Kansas": "061",
        "Gem County, Idaho": "045",
        "Geneva County, Alabama": "061",
        "Gibson County, Indiana": "051",
        "Gila County, Arizona": "007",
        "Gilchrist County, Florida": "041",
        "Gilmer County, Georgia": "123",
        "Gilpin County, Colorado": "047",
        "Glades County, Florida": "043",
        "Glascock County, Georgia": "125",
        "Glenn County, California": "021",
        "Glynn County, Georgia": "127",
        "Gooding County, Idaho": "047",
        "Gordon County, Georgia": "129",
        "Gove County, Kansas": "063",
        "Grady County, Georgia": "131",
        "Graham County, Arizona": "009",
        "Graham County, Kansas": "065",
        "Grand County, Colorado": "049",
        "Grant County, Arkansas": "053",
        "Grant County, Indiana": "053",
        "Grant County, Kansas": "067",
        "Gray County, Kansas": "069",
        "Greater Bridgeport Planning Region, Connecticut": "120",
        "Greeley County, Kansas": "071",
        "Greene County, Alabama": "063",
        "Greene County, Arkansas": "055",
        "Greene County, Georgia": "133",
        "Greene County, Illinois": "061",
        "Greene County, Indiana": "055",
        "Greene County, Iowa": "073",
        "Greenlee County, Arizona": "011",
        "Greenwood County, Kansas": "073",
        "Grundy County, Illinois": "063",
        "Grundy County, Iowa": "075",
        "Gulf County, Florida": "045",
        "Gunnison County, Colorado": "051",
        "Guthrie County, Iowa": "077",
        "Gwinnett County, Georgia": "135",
        "Habersham County, Georgia": "137",
        "Haines Borough, Alaska": "100",
        "Hale County, Alabama": "065",
        "Hall County, Georgia": "139",
        "Hamilton County, Florida": "047",
        "Hamilton County, Illinois": "065",
        "Hamilton County, Indiana": "057",
        "Hamilton County, Iowa": "079",
        "Hamilton County, Kansas": "075",
        "Hancock County, Georgia": "141",
        "Hancock County, Illinois": "067",
        "Hancock County, Indiana": "059",
        "Hancock County, Iowa": "081",
        "Haralson County, Georgia": "143",
        "Hardee County, Florida": "049",
        "Hardin County, Illinois": "069",
        "Hardin County, Iowa": "083",
        "Harper County, Kansas": "077",
        "Harris County, Georgia": "145",
        "Harrison County, Indiana": "061",
        "Harrison County, Iowa": "085",
        "Hart County, Georgia": "147",
        "Harvey County, Kansas": "079",
        "Haskell County, Kansas": "081",
        "Hawaii County, Hawaii": "001",
        "Heard County, Georgia": "149",
        "Hempstead County, Arkansas": "057",
        "Henderson County, Illinois": "071",
        "Hendricks County, Indiana": "063",
        "Hendry County, Florida": "051",
        "Henry County, Alabama": "067",
        "Henry County, Georgia": "151",
        "Henry County, Illinois": "073",
        "Henry County, Indiana": "065",
        "Henry County, Iowa": "087",
        "Hernando County, Florida": "053",
        "Highlands County, Florida": "055",
        "Hillsborough County, Florida": "057",
        "Hinsdale County, Colorado": "053",
        "Hodgeman County, Kansas": "083",
        "Holmes County, Florida": "059",
        "Honolulu County, Hawaii": "003",
        "Hoonah-Angoon Census Area, Alaska": "105",
        "Hot Spring County, Arkansas": "059",
        "Houston County, Alabama": "069",
        "Houston County, Georgia": "153",
        "Howard County, Arkansas": "061",
        "Howard County, Indiana": "067",
        "Howard County, Iowa": "089",
        "Huerfano County, Colorado": "055",
        "Humboldt County, California": "023",
        "Humboldt County, Iowa": "091",
        "Huntington County, Indiana": "069",
        "Ida County, Iowa": "093",
        "Idaho County, Idaho": "049",
        "Imperial County, California": "025",
        "Independence County, Arkansas": "063",
        "Indian River County, Florida": "061",
        "Inyo County, California": "027",
        "Iowa County, Iowa": "095",
        "Iroquois County, Illinois": "075",
        "Irwin County, Georgia": "155",
        "Izard County, Arkansas": "065",
        "Jackson County, Alabama": "071",
        "Jackson County, Arkansas": "067",
        "Jackson County, Colorado": "057",
        "Jackson County, Florida": "063",
        "Jackson County, Georgia": "157",
        "Jackson County, Illinois": "077",
        "Jackson County, Indiana": "071",
        "Jackson County, Iowa": "097",
        "Jackson County, Kansas": "085",
        "Jasper County, Georgia": "159",
        "Jasper County, Illinois": "079",
        "Jasper County, Indiana": "073",
        "Jasper County, Iowa": "099",
        "Jay County, Indiana": "075",
        "Jeff Davis County, Georgia": "161",
        "Jefferson County, Alabama": "073",
        "Jefferson County, Arkansas": "069",
        "Jefferson County, Colorado": "059",
        "Jefferson County, Florida": "065",
        "Jefferson County, Georgia": "163",
        "Jefferson County, Idaho": "051",
        "Jefferson County, Illinois": "081",
        "Jefferson County, Indiana": "077",
        "Jefferson County, Iowa": "101",
        "Jefferson County, Kansas": "087",
        "Jenkins County, Georgia": "165",
        "Jennings County, Indiana": "079",
        "Jerome County, Idaho": "053",
        "Jersey County, Illinois": "083",
        "Jewell County, Kansas": "089",
        "Jo Daviess County, Illinois": "085",
        "Johnson County, Arkansas": "071",
        "Johnson County, Georgia": "167",
        "Johnson County, Illinois": "087",
        "Johnson County, Indiana": "081",
        "Johnson County, Iowa": "103",
        "Jones County, Georgia": "169",
        "Jones County, Iowa": "105",
        "Juneau City and Borough, Alaska": "110",
        "Kalawao County, Hawaii": "005",
        "Kane County, Illinois": "089",
        "Kankakee County, Illinois": "091",
        "Kauai County, Hawaii": "007",
        "Kenai Peninsula Borough, Alaska": "122",
        "Kendall County, Illinois": "093",
        "Kent County, Delaware": "001",
        "Keokuk County, Iowa": "107",
        "Kern County, California": "029",
        "Ketchikan Gateway Borough, Alaska": "130",
        "Kings County, California": "031",
        "Kiowa County, Colorado": "061",
        "Kit Carson County, Colorado": "063",
        "Knox County, Illinois": "095",
        "Knox County, Indiana": "083",
        "Kodiak Island Borough, Alaska": "150",
        "Kootenai County, Idaho": "055",
        "Kosciusko County, Indiana": "085",
        "Kossuth County, Iowa": "109",
        "Kusilvak Census Area, Alaska": "158",
        "La Paz County, Arizona": "012",
        "La Plata County, Colorado": "067",
        "LaGrange County, Indiana": "087",
        "LaPorte County, Indiana": "091",
        "LaSalle County, Illinois": "099",
        "Lafayette County, Arkansas": "073",
        "Lafayette County, Florida": "067",
        "Lake County, California": "033",
        "Lake County, Colorado": "065",
        "Lake County, Florida": "069",
        "Lake County, Illinois": "097",
        "Lake County, Indiana": "089",
        "Lake and Peninsula Borough, Alaska": "164",
        "Lamar County, Alabama": "075",
        "Lamar County, Georgia": "171",
        "Lanier County, Georgia": "173",
        "Larimer County, Colorado": "069",
        "Las Animas County, Colorado": "071",
        "Lassen County, California": "035",
        "Latah County, Idaho": "057",
        "Lauderdale County, Alabama": "077",
        "Laurens County, Georgia": "175",
        "Lawrence County, Alabama": "079",
        "Lawrence County, Arkansas": "075",
        "Lawrence County, Illinois": "101",
        "Lawrence County, Indiana": "093",
        "Lee County, Alabama": "081",
        "Lee County, Arkansas": "077",
        "Lee County, Florida": "071",
        "Lee County, Georgia": "177",
        "Lee County, Illinois": "103",
        "Lee County, Iowa": "111",
        "Lemhi County, Idaho": "059",
        "Leon County, Florida": "073",
        "Levy County, Florida": "075",
        "Lewis County, Idaho": "061",
        "Liberty County, Florida": "077",
        "Liberty County, Georgia": "179",
        "Limestone County, Alabama": "083",
        "Lincoln County, Arkansas": "079",
        "Lincoln County, Colorado": "073",
        "Lincoln County, Georgia": "181",
        "Lincoln County, Idaho": "063",
        "Linn County, Iowa": "113",
        "Little River County, Arkansas": "081",
        "Livingston County, Illinois": "105",
        "Logan County, Arkansas": "083",
        "Logan County, Colorado": "075",
        "Logan County, Illinois": "107",
        "Long County, Georgia": "183",
        "Lonoke County, Arkansas": "085",
        "Los Angeles County, California": "037",
        "Louisa County, Iowa": "115",
        "Lower Connecticut River Valley Planning Region, Connecticut": "130",
        "Lowndes County, Alabama": "085",
        "Lowndes County, Georgia": "185",
        "Lucas County, Iowa": "117",
        "Lumpkin County, Georgia": "187",
        "Lyon County, Iowa": "119",
        "Macon County, Alabama": "087",
        "Macon County, Georgia": "193",
        "Macon County, Illinois": "115",
        "Macoupin County, Illinois": "117",
        "Madera County, California": "039",
        "Madison County, Alabama": "089",
        "Madison County, Arkansas": "087",
        "Madison County, Florida": "079",
        "Madison County, Georgia": "195",
        "Madison County, Idaho": "065",
        "Madison County, Illinois": "119",
        "Madison County, Indiana": "095",
        "Madison County, Iowa": "121",
        "Mahaska County, Iowa": "123",
        "Manatee County, Florida": "081",
        "Marengo County, Alabama": "091",
        "Maricopa County, Arizona": "013",
        "Marin County, California": "041",
        "Marion County, Alabama": "093",
        "Marion County, Arkansas": "089",
        "Marion County, Florida": "083",
        "Marion County, Georgia": "197",
        "Marion County, Illinois": "121",
        "Marion County, Indiana": "097",
        "Marion County, Iowa": "125",
        "Mariposa County, California": "043",
        "Marshall County, Alabama": "095",
        "Marshall County, Illinois": "123",
        "Marshall County, Indiana": "099",
        "Marshall County, Iowa": "127",
        "Martin County, Florida": "085",
        "Martin County, Indiana": "101",
        "Mason County, Illinois": "125",
        "Massac County, Illinois": "127",
        "Matanuska-Susitna Borough, Alaska": "170",
        "Maui County, Hawaii": "009",
        "McDonough County, Illinois": "109",
        "McDuffie County, Georgia": "189",
        "McHenry County, Illinois": "111",
        "McIntosh County, Georgia": "191",
        "McLean County, Illinois": "113",
        "Menard County, Illinois": "129",
        "Mendocino County, California": "045",
        "Merced County, California": "047",
        "Mercer County, Illinois": "131",
        "Meriwether County, Georgia": "199",
        "Mesa County, Colorado": "077",
        "Miami County, Indiana": "103",
        "Miami-Dade County, Florida": "086",
        "Miller County, Arkansas": "091",
        "Miller County, Georgia": "201",
        "Mills County, Iowa": "129",
        "Mineral County, Colorado": "079",
        "Minidoka County, Idaho": "067",
        "Mississippi County, Arkansas": "093",
        "Mitchell County, Georgia": "205",
        "Mitchell County, Iowa": "131",
        "Mobile County, Alabama": "097",
        "Modoc County, California": "049",
        "Moffat County, Colorado": "081",
        "Mohave County, Arizona": "015",
        "Mono County, California": "051",
        "Monona County, Iowa": "133",
        "Monroe County, Alabama": "099",
        "Monroe County, Arkansas": "095",
        "Monroe County, Florida": "087",
        "Monroe County, Georgia": "207",
        "Monroe County, Illinois": "133",
        "Monroe County, Indiana": "105",
        "Monroe County, Iowa": "135",
        "Monterey County, California": "053",
        "Montezuma County, Colorado": "083",
        "Montgomery County, Alabama": "101",
        "Montgomery County, Arkansas": "097",
        "Montgomery County, Georgia": "209",
        "Montgomery County, Illinois": "135",
        "Montgomery County, Indiana": "107",
        "Montgomery County, Iowa": "137",
        "Montrose County, Colorado": "085",
        "Morgan County, Alabama": "103",
        "Morgan County, Colorado": "087",
        "Morgan County, Georgia": "211",
        "Morgan County, Illinois": "137",
        "Morgan County, Indiana": "109",
        "Moultrie County, Illinois": "139",
        "Murray County, Georgia": "213",
        "Muscatine County, Iowa": "139",
        "Muscogee County, Georgia": "215",
        "Napa County, California": "055",
        "Nassau County, Florida": "089",
        "Naugatuck Valley Planning Region, Connecticut": "140",
        "Navajo County, Arizona": "017",
        "Nevada County, Arkansas": "099",
        "Nevada County, California": "057",
        "New Castle County, Delaware": "003",
        "Newton County, Arkansas": "101",
        "Newton County, Georgia": "217",
        "Newton County, Indiana": "111",
        "Nez Perce County, Idaho": "069",
        "Noble County, Indiana": "113",
        "Nome Census Area, Alaska": "180",
        "North Slope Borough, Alaska": "185",
        "Northeastern Connecticut Planning Region, Connecticut": "150",
        "Northwest Arctic Borough, Alaska": "188",
        "Northwest Hills Planning Region, Connecticut": "160",
        "O'Brien County, Iowa": "141",
        "Oconee County, Georgia": "219",
        "Ogle County, Illinois": "141",
        "Oglethorpe County, Georgia": "221",
        "Ohio County, Indiana": "115",
        "Okaloosa County, Florida": "091",
        "Okeechobee County, Florida": "093",
        "Oneida County, Idaho": "071",
        "Orange County, California": "059",
        "Orange County, Florida": "095",
        "Orange County, Indiana": "117",
        "Osceola County, Florida": "097",
        "Osceola County, Iowa": "143",
        "Otero County, Colorado": "089",
        "Ouachita County, Arkansas": "103",
        "Ouray County, Colorado": "091",
        "Owen County, Indiana": "119",
        "Owyhee County, Idaho": "073",
        "Page County, Iowa": "145",
        "Palm Beach County, Florida": "099",
        "Palo Alto County, Iowa": "147",
        "Park County, Colorado": "093",
        "Parke County, Indiana": "121",
        "Pasco County, Florida": "101",
        "Paulding County, Georgia": "223",
        "Payette County, Idaho": "075",
        "Peach County, Georgia": "225",
        "Peoria County, Illinois": "143",
        "Perry County, Alabama": "105",
        "Perry County, Arkansas": "105",
        "Perry County, Illinois": "145",
        "Perry County, Indiana": "123",
        "Petersburg Borough, Alaska": "195",
        "Phillips County, Arkansas": "107",
        "Phillips County, Colorado": "095",
        "Piatt County, Illinois": "147",
        "Pickens County, Alabama": "107",
        "Pickens County, Georgia": "227",
        "Pierce County, Georgia": "229",
        "Pike County, Alabama": "109",
        "Pike County, Arkansas": "109",
        "Pike County, Georgia": "231",
        "Pike County, Illinois": "149",
        "Pike County, Indiana": "125",
        "Pima County, Arizona": "019",
        "Pinal County, Arizona": "021",
        "Pinellas County, Florida": "103",
        "Pitkin County, Colorado": "097",
        "Placer County, California": "061",
        "Plumas County, California": "063",
        "Plymouth County, Iowa": "149",
        "Pocahontas County, Iowa": "151",
        "Poinsett County, Arkansas": "111",
        "Polk County, Arkansas": "113",
        "Polk County, Florida": "105",
        "Polk County, Georgia": "233",
        "Polk County, Iowa": "153",
        "Pope County, Arkansas": "115",
        "Pope County, Illinois": "151",
        "Porter County, Indiana": "127",
        "Posey County, Indiana": "129",
        "Pottawattamie County, Iowa": "155",
        "Power County, Idaho": "077",
        "Poweshiek County, Iowa": "157",
        "Prairie County, Arkansas": "117",
        "Prince of Wales-Hyder Census Area, Alaska": "198",
        "Prowers County, Colorado": "099",
        "Pueblo County, Colorado": "101",
        "Pulaski County, Arkansas": "119",
        "Pulaski County, Georgia": "235",
        "Pulaski County, Illinois": "153",
        "Pulaski County, Indiana": "131",
        "Putnam County, Florida": "107",
        "Putnam County, Georgia": "237",
        "Putnam County, Illinois": "155",
        "Putnam County, Indiana": "133",
        "Quitman County, Georgia": "239",
        "Rabun County, Georgia": "241",
        "Randolph County, Alabama": "111",
        "Randolph County, Arkansas": "121",
        "Randolph County, Georgia": "243",
        "Randolph County, Illinois": "157",
        "Randolph County, Indiana": "135",
        "Richland County, Illinois": "159",
        "Richmond County, Georgia": "245",
        "Ringgold County, Iowa": "159",
        "Rio Blanco County, Colorado": "103",
        "Rio Grande County, Colorado": "105",
        "Ripley County, Indiana": "137",
        "Riverside County, California": "065",
        "Rock Island County, Illinois": "161",
        "Rockdale County, Georgia": "247",
        "Routt County, Colorado": "107",
        "Rush County, Indiana": "139",
        "Russell County, Alabama": "113",
        "Sac County, Iowa": "161",
        "Sacramento County, California": "067",
        "Saguache County, Colorado": "109",
        "Saline County, Arkansas": "125",
        "Saline County, Illinois": "165",
        "San Benito County, California": "069",
        "San Bernardino County, California": "071",
        "San Diego County, California": "073",
        "San Francisco County, California": "075",
        "San Joaquin County, California": "077",
        "San Juan County, Colorado": "111",
        "San Luis Obispo County, California": "079",
        "San Mateo County, California": "081",
        "San Miguel County, Colorado": "113",
        "Sangamon County, Illinois": "167",
        "Santa Barbara County, California": "083",
        "Santa Clara County, California": "085",
        "Santa Cruz County, Arizona": "023",
        "Santa Cruz County, California": "087",
        "Santa Rosa County, Florida": "113",
        "Sarasota County, Florida": "115",
        "Schley County, Georgia": "249",
        "Schuyler County, Illinois": "169",
        "Scott County, Arkansas": "127",
        "Scott County, Illinois": "171",
        "Scott County, Indiana": "143",
        "Scott County, Iowa": "163",
        "Screven County, Georgia": "251",
        "Searcy County, Arkansas": "129",
        "Sebastian County, Arkansas": "131",
        "Sedgwick County, Colorado": "115",
        "Seminole County, Florida": "117",
        "Seminole County, Georgia": "253",
        "Sevier County, Arkansas": "133",
        "Sharp County, Arkansas": "135",
        "Shasta County, California": "089",
        "Shelby County, Alabama": "117",
        "Shelby County, Illinois": "173",
        "Shelby County, Indiana": "145",
        "Shelby County, Iowa": "165",
        "Shoshone County, Idaho": "079",
        "Sierra County, California": "091",
        "Sioux County, Iowa": "167",
        "Siskiyou County, California": "093",
        "Sitka City and Borough, Alaska": "220",
        "Skagway Municipality, Alaska": "230",
        "Solano County, California": "095",
        "Sonoma County, California": "097",
        "South Central Connecticut Planning Region, Connecticut": "170",
        "Southeast Fairbanks Census Area, Alaska": "240",
        "Southeastern Connecticut Planning Region, Connecticut": "180",
        "Spalding County, Georgia": "255",
        "Spencer County, Indiana": "147",
        "St. Clair County, Alabama": "115",
        "St. Clair County, Illinois": "163",
        "St. Francis County, Arkansas": "123",
        "St. Johns County, Florida": "109",
        "St. Joseph County, Indiana": "141",
        "St. Lucie County, Florida": "111",
        "Stanislaus County, California": "099",
        "Stark County, Illinois": "175",
        "Starke County, Indiana": "149",
        "Stephens County, Georgia": "257",
        "Stephenson County, Illinois": "177",
        "Steuben County, Indiana": "151",
        "Stewart County, Georgia": "259",
        "Stone County, Arkansas": "137",
        "Story County, Iowa": "169",
        "Sullivan County, Indiana": "153",
        "Summit County, Colorado": "117",
        "Sumter County, Alabama": "119",
        "Sumter County, Florida": "119",
        "Sumter County, Georgia": "261",
        "Sussex County, Delaware": "005",
        "Sutter County, California": "101",
        "Suwannee County, Florida": "121",
        "Switzerland County, Indiana": "155",
        "Talbot County, Georgia": "263",
        "Taliaferro County, Georgia": "265",
        "Talladega County, Alabama": "121",
        "Tallapoosa County, Alabama": "123",
        "Tama County, Iowa": "171",
        "Tattnall County, Georgia": "267",
        "Taylor County, Florida": "123",
        "Taylor County, Georgia": "269",
        "Taylor County, Iowa": "173",
        "Tazewell County, Illinois": "179",
        "Tehama County, California": "103",
        "Telfair County, Georgia": "271",
        "Teller County, Colorado": "119",
        "Terrell County, Georgia": "273",
        "Teton County, Idaho": "081",
        "Thomas County, Georgia": "275",
        "Tift County, Georgia": "277",
        "Tippecanoe County, Indiana": "157",
        "Tipton County, Indiana": "159",
        "Toombs County, Georgia": "279",
        "Towns County, Georgia": "281",
        "Treutlen County, Georgia": "283",
        "Trinity County, California": "105",
        "Troup County, Georgia": "285",
        "Tulare County, California": "107",
        "Tuolumne County, California": "109",
        "Turner County, Georgia": "287",
        "Tuscaloosa County, Alabama": "125",
        "Twiggs County, Georgia": "289",
        "Twin Falls County, Idaho": "083",
        "Union County, Arkansas": "139",
        "Union County, Florida": "125",
        "Union County, Georgia": "291",
        "Union County, Illinois": "181",
        "Union County, Indiana": "161",
        "Union County, Iowa": "175",
        "Upson County, Georgia": "293",
        "Valley County, Idaho": "085",
        "Van Buren County, Arkansas": "141",
        "Van Buren County, Iowa": "177",
        "Vanderburgh County, Indiana": "163",
        "Ventura County, California": "111",
        "Vermilion County, Illinois": "183",
        "Vermillion County, Indiana": "165",
        "Vigo County, Indiana": "167",
        "Volusia County, Florida": "127",
        "Wabash County, Illinois": "185",
        "Wabash County, Indiana": "169",
        "Wakulla County, Florida": "129",
        "Walker County, Alabama": "127",
        "Walker County, Georgia": "295",
        "Walton County, Florida": "131",
        "Walton County, Georgia": "297",
        "Wapello County, Iowa": "179",
        "Ware County, Georgia": "299",
        "Warren County, Georgia": "301",
        "Warren County, Illinois": "187",
        "Warren County, Indiana": "171",
        "Warren County, Iowa": "181",
        "Warrick County, Indiana": "173",
        "Washington County, Alabama": "129",
        "Washington County, Arkansas": "143",
        "Washington County, Colorado": "121",
        "Washington County, Florida": "133",
        "Washington County, Georgia": "303",
        "Washington County, Idaho": "087",
        "Washington County, Illinois": "189",
        "Washington County, Indiana": "175",
        "Washington County, Iowa": "183",
        "Wayne County, Georgia": "305",
        "Wayne County, Illinois": "191",
        "Wayne County, Indiana": "177",
        "Wayne County, Iowa": "185",
        "Webster County, Georgia": "307",
        "Webster County, Iowa": "187",
        "Weld County, Colorado": "123",
        "Wells County, Indiana": "179",
        "Western Connecticut Planning Region, Connecticut": "190",
        "Wheeler County, Georgia": "309",
        "White County, Arkansas": "145",
        "White County, Georgia": "311",
        "White County, Illinois": "193",
        "White County, Indiana": "181",
        "Whiteside County, Illinois": "195",
        "Whitfield County, Georgia": "313",
        "Whitley County, Indiana": "183",
        "Wilcox County, Alabama": "131",
        "Wilcox County, Georgia": "315",
        "Wilkes County, Georgia": "317",
        "Wilkinson County, Georgia": "319",
        "Will County, Illinois": "197",
        "Williamson County, Illinois": "199",
        "Winnebago County, Illinois": "201",
        "Winnebago County, Iowa": "189",
        "Winneshiek County, Iowa": "191",
        "Winston County, Alabama": "133",
        "Woodbury County, Iowa": "193",
        "Woodford County, Illinois": "203",
        "Woodruff County, Arkansas": "147",
        "Worth County, Georgia": "321",
        "Worth County, Iowa": "195",
        "Wrangell City and Borough, Alaska": "275",
        "Wright County, Iowa": "197",
        "Yakutat City and Borough, Alaska": "282",
        "Yavapai County, Arizona": "025",
        "Yell County, Arkansas": "149",
        "Yolo County, California": "113",
        "Yuba County, California": "115",
        "Yukon-Koyukuk Census Area, Alaska": "290",
        "Yuma County, Arizona": "027",
        "Yuma County, Colorado": "125",
    }

def search_county_fips(keyword: str, max_results: Optional[int] = 20) -> List[Tuple[str, str]]:
    """
    Search for counties by keyword and return their FIPS codes.
    
    Supports flexible multi-word searches. Results are prioritized by match quality:
    1. Exact word matches (e.g., "cook" → "Cook County")
    2. All words match (e.g., "cook county illinois" → "Cook County, Illinois") 
    3. Partial matches (e.g., "coo" → "Cook County")
    
    Args:
        keyword (str): Search term(s) to match against county names (case-insensitive)
        max_results (Optional[int]): Maximum number of results to return (default: 20)
    
    Returns:
        List[Tuple[str, str]]: List of (county_name, fips_code) tuples matching the search
        
    Examples:
        >>> search_county_fips("cook")
        [("Cook County, Georgia", "075"), ("Cook County, Illinois", "031")]
        
        >>> search_county_fips("cook county illinois")
        [("Cook County, Illinois", "031")]
        
        >>> search_county_fips("jefferson county colorado")
        [("Jefferson County, Colorado", "059")]
    """
    if not keyword or not keyword.strip():
        return []
    
    keyword = keyword.strip().lower()
    county_data = _get_county_fips_data()
    
    # Split the search query into individual terms
    search_terms = re.split(r'\W+', keyword)
    search_terms = [term for term in search_terms if term]  # Remove empty strings
    
    # Find matches with different priority levels
    exact_matches = []
    all_word_matches = []
    partial_matches = []
    
    for county_name, fips_code in county_data.items():
        county_lower = county_name.lower()
        county_words = re.split(r'\W+', county_lower)
        
        # Priority 1: Single term that exactly matches a word in the county name
        if len(search_terms) == 1 and search_terms[0] in county_words:
            exact_matches.append((county_name, fips_code))
        # Priority 2: All search terms appear as words in the county name
        elif len(search_terms) > 1 and all(term in county_words for term in search_terms):
            all_word_matches.append((county_name, fips_code))
        # Priority 3: All search terms appear somewhere in the county name (substring match)
        elif all(term in county_lower for term in search_terms):
            partial_matches.append((county_name, fips_code))
    
    # Combine results, prioritizing exact matches, then all-word matches, then partial matches
    results = exact_matches + all_word_matches + partial_matches
    
    # Apply max_results limit
    if max_results and max_results > 0:
        results = results[:max_results]
    
    return results