from typing import Dict, List, Tuple, Optional, Union
import re

"""
OEWS SOC Search Tool

This module provides a keyword search function to find SOC (Standard Occupational Classification) codes.
It searches through occupation titles and returns matching results with their SOC codes.
This is designed for use as an LLM tool to provide manageable result sets.
"""

def _get_soc_data() -> Dict[str, str]:
    soc_dictionary: Dict[str, str] = {
        "000000": "All Occupations",
        "111011": "Chief Executives",
        "111021": "General and Operations Managers",
        "111031": "Legislators",
        "112011": "Advertising and Promotions Managers",
        "112021": "Marketing Managers",
        "112022": "Sales Managers",
        "112032": "Public Relations Managers",
        "112033": "Fundraising Managers",
        "113012": "Administrative Services Managers",
        "113013": "Facilities Managers",
        "113021": "Computer and Information Systems Managers",
        "113031": "Financial Managers",
        "113051": "Industrial Production Managers",
        "113061": "Purchasing Managers",
        "113071": "Transportation, Storage, and Distribution Managers",
        "113111": "Compensation and Benefits Managers",
        "113121": "Human Resources Managers",
        "113131": "Training and Development Managers",
        "119013": "Farmers, Ranchers, and Other Agricultural Managers",
        "119021": "Construction Managers",
        "119031": "Education and Childcare Administrators, Preschool and Daycare",
        "119032": "Education Administrators, Kindergarten through Secondary",
        "119033": "Education Administrators, Postsecondary",
        "119039": "Education Administrators, All Other",
        "119041": "Architectural and Engineering Managers",
        "119051": "Food Service Managers",
        "119071": "Gambling Managers",
        "119072": "Entertainment and Recreation Managers, Except Gambling",
        "119081": "Lodging Managers",
        "119111": "Medical and Health Services Managers",
        "119121": "Natural Sciences Managers",
        "119131": "Postmasters and Mail Superintendents",
        "119141": "Property, Real Estate, and Community Association Managers",
        "119151": "Social and Community Service Managers",
        "119161": "Emergency Management Directors",
        "119171": "Funeral Home Managers",
        "119179": "Personal Service Managers, All Other",
        "119199": "Managers, All Other",
        "131011": "Agents and Business Managers of Artists, Performers, and Athletes",
        "131031": "Claims Adjusters, Examiners, and Investigators",
        "131032": "Insurance Appraisers, Auto Damage",
        "131041": "Compliance Officers",
        "131051": "Cost Estimators",
        "131071": "Human Resources Specialists",
        "131074": "Farm Labor Contractors",
        "131075": "Labor Relations Specialists",
        "131081": "Logisticians",
        "131082": "Project Management Specialists",
        "131111": "Management Analysts",
        "131121": "Meeting, Convention, and Event Planners",
        "131131": "Fundraisers",
        "131141": "Compensation, Benefits, and Job Analysis Specialists",
        "131151": "Training and Development Specialists",
        "131161": "Market Research Analysts and Marketing Specialists",
        "131199": "Business Operations Specialists, All Other",
        "132011": "Accountants and Auditors",
        "132031": "Budget Analysts",
        "132041": "Credit Analysts",
        "132051": "Financial and Investment Analysts",
        "132052": "Personal Financial Advisors",
        "132053": "Insurance Underwriters",
        "132054": "Financial Risk Specialists",
        "132061": "Financial Examiners",
        "132071": "Credit Counselors",
        "132072": "Loan Officers",
        "132081": "Tax Examiners and Collectors, and Revenue Agents",
        "132082": "Tax Preparers",
        "132099": "Financial Specialists, All Other",
        "151211": "Computer Systems Analysts",
        "151212": "Information Security Analysts",
        "151221": "Computer and Information Research Scientists",
        "151231": "Computer Network Support Specialists",
        "151232": "Computer User Support Specialists",
        "151241": "Computer Network Architects",
        "151242": "Database Administrators",
        "151243": "Database Architects",
        "151244": "Network and Computer Systems Administrators",
        "151251": "Computer Programmers",
        "151252": "Software Developers",
        "151253": "Software Quality Assurance Analysts and Testers",
        "151254": "Web Developers",
        "151255": "Web and Digital Interface Designers",
        "151299": "Computer Occupations, All Other",
        "152011": "Actuaries",
        "152021": "Mathematicians",
        "152031": "Operations Research Analysts",
        "152041": "Statisticians",
        "152051": "Data Scientists",
        "152099": "Mathematical Science Occupations, All Other",
        "171011": "Architects, Except Landscape and Naval",
        "171012": "Landscape Architects",
        "171021": "Cartographers and Photogrammetrists",
        "171022": "Surveyors",
        "172011": "Aerospace Engineers",
        "172021": "Agricultural Engineers",
        "172031": "Bioengineers and Biomedical Engineers",
        "172041": "Chemical Engineers",
        "172051": "Civil Engineers",
        "172061": "Computer Hardware Engineers",
        "172071": "Electrical Engineers",
        "172072": "Electronics Engineers, Except Computer",
        "172081": "Environmental Engineers",
        "172111": "Health and Safety Engineers, Except Mining Safety Engineers and Inspectors",
        "172112": "Industrial Engineers",
        "172121": "Marine Engineers and Naval Architects",
        "172131": "Materials Engineers",
        "172141": "Mechanical Engineers",
        "172151": "Mining and Geological Engineers, Including Mining Safety Engineers",
        "172161": "Nuclear Engineers",
        "172171": "Petroleum Engineers",
        "172199": "Engineers, All Other",
        "173011": "Architectural and Civil Drafters",
        "173012": "Electrical and Electronics Drafters",
        "173013": "Mechanical Drafters",
        "173019": "Drafters, All Other",
        "173021": "Aerospace Engineering and Operations Technologists and Technicians",
        "173022": "Civil Engineering Technologists and Technicians",
        "173023": "Electrical and Electronic Engineering Technologists and Technicians",
        "173024": "Electro-Mechanical and Mechatronics Technologists and Technicians",
        "173025": "Environmental Engineering Technologists and Technicians",
        "173026": "Industrial Engineering Technologists and Technicians",
        "173027": "Mechanical Engineering Technologists and Technicians",
        "173028": "Calibration Technologists and Technicians",
        "173029": "Engineering Technologists and Technicians, Except Drafters, All Other",
        "173031": "Surveying and Mapping Technicians",
        "191011": "Animal Scientists",
        "191012": "Food Scientists and Technologists",
        "191013": "Soil and Plant Scientists",
        "191021": "Biochemists and Biophysicists",
        "191022": "Microbiologists",
        "191023": "Zoologists and Wildlife Biologists",
        "191029": "Biological Scientists, All Other",
        "191031": "Conservation Scientists",
        "191032": "Foresters",
        "191041": "Epidemiologists",
        "191042": "Medical Scientists, Except Epidemiologists",
        "191099": "Life Scientists, All Other",
        "192011": "Astronomers",
        "192012": "Physicists",
        "192021": "Atmospheric and Space Scientists",
        "192031": "Chemists",
        "192032": "Materials Scientists",
        "192041": "Environmental Scientists and Specialists, Including Health",
        "192042": "Geoscientists, Except Hydrologists and Geographers",
        "192043": "Hydrologists",
        "192099": "Physical Scientists, All Other",
        "193011": "Economists",
        "193022": "Survey Researchers",
        "193032": "Industrial-Organizational Psychologists",
        "193033": "Clinical and Counseling Psychologists",
        "193034": "School Psychologists",
        "193039": "Psychologists, All Other",
        "193041": "Sociologists",
        "193051": "Urban and Regional Planners",
        "193091": "Anthropologists and Archeologists",
        "193092": "Geographers",
        "193093": "Historians",
        "193094": "Political Scientists",
        "193099": "Social Scientists and Related Workers, All Other",
        "194012": "Agricultural Technicians",
        "194013": "Food Science Technicians",
        "194021": "Biological Technicians",
        "194031": "Chemical Technicians",
        "194042": "Environmental Science and Protection Technicians, Including Health",
        "194043": "Geological Technicians, Except Hydrologic Technicians",
        "194044": "Hydrologic Technicians",
        "194051": "Nuclear Technicians",
        "194061": "Social Science Research Assistants",
        "194071": "Forest and Conservation Technicians",
        "194092": "Forensic Science Technicians",
        "194099": "Life, Physical, and Social Science Technicians, All Other",
        "195011": "Occupational Health and Safety Specialists",
        "195012": "Occupational Health and Safety Technicians",
        "211012": "Educational, Guidance, and Career Counselors and Advisors",
        "211013": "Marriage and Family Therapists",
        "211015": "Rehabilitation Counselors",
        "211018": "Substance abuse, behavioral disorder, and mental health counselors",
        "211019": "Counselors, All Other",
        "211021": "Child, Family, and School Social Workers",
        "211022": "Healthcare Social Workers",
        "211023": "Mental Health and Substance Abuse Social Workers",
        "211029": "Social Workers, All Other",
        "211091": "Health Education Specialists",
        "211092": "Probation Officers and Correctional Treatment Specialists",
        "211093": "Social and Human Service Assistants",
        "211094": "Community Health Workers",
        "211099": "Community and Social Service Specialists, All Other",
        "212011": "Clergy",
        "212021": "Directors, Religious Activities and Education",
        "212099": "Religious Workers, All Other",
        "231011": "Lawyers",
        "231012": "Judicial Law Clerks",
        "231021": "Administrative Law Judges, Adjudicators, and Hearing Officers",
        "231022": "Arbitrators, Mediators, and Conciliators",
        "231023": "Judges, Magistrate Judges, and Magistrates",
        "232011": "Paralegals and Legal Assistants",
        "232093": "Title Examiners, Abstractors, and Searchers",
        "232099": "Legal Support Workers, All Other",
        "251011": "Business Teachers, Postsecondary",
        "251021": "Computer Science Teachers, Postsecondary",
        "251022": "Mathematical Science Teachers, Postsecondary",
        "251031": "Architecture Teachers, Postsecondary",
        "251032": "Engineering Teachers, Postsecondary",
        "251041": "Agricultural Sciences Teachers, Postsecondary",
        "251042": "Biological Science Teachers, Postsecondary",
        "251043": "Forestry and Conservation Science Teachers, Postsecondary",
        "251051": "Atmospheric, Earth, Marine, and Space Sciences Teachers, Postsecondary",
        "251052": "Chemistry Teachers, Postsecondary",
        "251053": "Environmental Science Teachers, Postsecondary",
        "251054": "Physics Teachers, Postsecondary",
        "251061": "Anthropology and Archeology Teachers, Postsecondary",
        "251062": "Area, Ethnic, and Cultural Studies Teachers, Postsecondary",
        "251063": "Economics Teachers, Postsecondary",
        "251064": "Geography Teachers, Postsecondary",
        "251065": "Political Science Teachers, Postsecondary",
        "251066": "Psychology Teachers, Postsecondary",
        "251067": "Sociology Teachers, Postsecondary",
        "251069": "Social Sciences Teachers, Postsecondary, All Other",
        "251071": "Health Specialties Teachers, Postsecondary",
        "251072": "Nursing Instructors and Teachers, Postsecondary",
        "251081": "Education Teachers, Postsecondary",
        "251082": "Library Science Teachers, Postsecondary",
        "251111": "Criminal Justice and Law Enforcement Teachers, Postsecondary",
        "251112": "Law Teachers, Postsecondary",
        "251113": "Social Work Teachers, Postsecondary",
        "251121": "Art, Drama, and Music Teachers, Postsecondary",
        "251122": "Communications Teachers, Postsecondary",
        "251123": "English Language and Literature Teachers, Postsecondary",
        "251124": "Foreign Language and Literature Teachers, Postsecondary",
        "251125": "History Teachers, Postsecondary",
        "251126": "Philosophy and Religion Teachers, Postsecondary",
        "251192": "Family and Consumer Sciences Teachers, Postsecondary",
        "251193": "Recreation and Fitness Studies Teachers, Postsecondary",
        "251194": "Career/Technical Education Teachers, Postsecondary",
        "251199": "Postsecondary Teachers, All Other",
        "252011": "Preschool Teachers, Except Special Education",
        "252012": "Kindergarten Teachers, Except Special Education",
        "252021": "Elementary School Teachers, Except Special Education",
        "252022": "Middle School Teachers, Except Special and Career/Technical Education",
        "252023": "Career/Technical Education Teachers, Middle School",
        "252031": "Secondary School Teachers, Except Special and Career/Technical Education",
        "252032": "Career/Technical Education Teachers, Secondary School",
        "252051": "Special Education Teachers, Preschool",
        "252052": "Special Education Teachers, Kindergarten and Elementary School",
        "252057": "Special Education Teachers, Middle School",
        "252058": "Special Education Teachers, Secondary School",
        "252059": "Special Education Teachers, All Other",
        "253011": "Adult Basic Education, Adult Secondary Education, and English as a Second Language Instructors",
        "253021": "Self-Enrichment Teachers",
        "253031": "Substitute Teachers, Short-Term",
        "253041": "Tutors",
        "253099": "Teachers and Instructors, All Other",
        "254011": "Archivists",
        "254012": "Curators",
        "254013": "Museum Technicians and Conservators",
        "254022": "Librarians and Media Collections Specialists",
        "254031": "Library Technicians",
        "259021": "Farm and Home Management Educators",
        "259031": "Instructional Coordinators",
        "259044": "Teaching Assistants, Postsecondary",
        "259045": "Teaching Assistants, Except Postsecondary",
        "259099": "Educational Instruction and Library Workers, All Other",
        "271011": "Art Directors",
        "271012": "Craft Artists",
        "271013": "Fine Artists, Including Painters, Sculptors, and Illustrators",
        "271014": "Special Effects Artists and Animators",
        "271019": "Artists and Related Workers, All Other",
        "271021": "Commercial and Industrial Designers",
        "271022": "Fashion Designers",
        "271023": "Floral Designers",
        "271024": "Graphic Designers",
        "271025": "Interior Designers",
        "271026": "Merchandise Displayers and Window Trimmers",
        "271027": "Set and Exhibit Designers",
        "271029": "Designers, All Other",
        "272011": "Actors",
        "272012": "Producers and Directors",
        "272021": "Athletes and Sports Competitors",
        "272022": "Coaches and Scouts",
        "272023": "Umpires, Referees, and Other Sports Officials",
        "272031": "Dancers",
        "272032": "Choreographers",
        "272041": "Music Directors and Composers",
        "272042": "Musicians and Singers",
        "272091": "Disc Jockeys, Except Radio",
        "272099": "Entertainers and Performers, Sports and Related Workers, All Other",
        "273011": "Broadcast Announcers and Radio Disc Jockeys",
        "273023": "News Analysts, Reporters, and Journalists",
        "273031": "Public Relations Specialists",
        "273041": "Editors",
        "273042": "Technical Writers",
        "273043": "Writers and Authors",
        "273091": "Interpreters and Translators",
        "273092": "Court Reporters and Simultaneous Captioners",
        "273099": "Media and Communication Workers, All Other",
        "274011": "Audio and Video Technicians",
        "274012": "Broadcast Technicians",
        "274014": "Sound Engineering Technicians",
        "274015": "Lighting Technicians",
        "274021": "Photographers",
        "274031": "Camera Operators, Television, Video, and Film",
        "274032": "Film and Video Editors",
        "274099": "Media and Communication Equipment Workers, All Other",
        "291011": "Chiropractors",
        "291021": "Dentists, General",
        "291022": "Oral and Maxillofacial Surgeons",
        "291023": "Orthodontists",
        "291024": "Prosthodontists",
        "291029": "Dentists, All Other Specialists",
        "291031": "Dietitians and Nutritionists",
        "291041": "Optometrists",
        "291051": "Pharmacists",
        "291071": "Physician Assistants",
        "291081": "Podiatrists",
        "291122": "Occupational Therapists",
        "291123": "Physical Therapists",
        "291124": "Radiation Therapists",
        "291125": "Recreational Therapists",
        "291126": "Respiratory Therapists",
        "291127": "Speech-Language Pathologists",
        "291128": "Exercise Physiologists",
        "291129": "Therapists, All Other",
        "291131": "Veterinarians",
        "291141": "Registered Nurses",
        "291151": "Nurse Anesthetists",
        "291161": "Nurse Midwives",
        "291171": "Nurse Practitioners",
        "291181": "Audiologists",
        "291211": "Anesthesiologists",
        "291212": "Cardiologists",
        "291213": "Dermatologists",
        "291214": "Emergency Medicine Physicians",
        "291215": "Family Medicine Physicians",
        "291216": "General Internal Medicine Physicians",
        "291217": "Neurologists",
        "291218": "Obstetricians and Gynecologists",
        "291221": "Pediatricians, General",
        "291222": "Physicians, Pathologists",
        "291223": "Psychiatrists",
        "291224": "Radiologists",
        "291229": "Physicians, All Other",
        "291241": "Ophthalmologists, Except Pediatric",
        "291242": "Orthopedic Surgeons, Except Pediatric",
        "291243": "Pediatric Surgeons",
        "291249": "Surgeons, All Other",
        "291291": "Acupuncturists",
        "291292": "Dental Hygienists",
        "291299": "Healthcare Diagnosing or Treating Practitioners, All Other",
        "292031": "Cardiovascular Technologists and Technicians",
        "292032": "Diagnostic Medical Sonographers",
        "292033": "Nuclear Medicine Technologists",
        "292034": "Radiologic Technologists and Technicians",
        "292035": "Magnetic Resonance Imaging Technologists",
        "292036": "Medical Dosimetrists",
        "292042": "Emergency Medical Technicians",
        "292043": "Paramedics",
        "292051": "Dietetic Technicians",
        "292052": "Pharmacy Technicians",
        "292053": "Psychiatric Technicians",
        "292055": "Surgical Technologists",
        "292056": "Veterinary Technologists and Technicians",
        "292057": "Ophthalmic Medical Technicians",
        "292061": "Licensed Practical and Licensed Vocational Nurses",
        "292072": "Medical Records Specialists",
        "292081": "Opticians, Dispensing",
        "292091": "Orthotists and Prosthetists",
        "292092": "Hearing Aid Specialists",
        "292099": "Health Technologists and Technicians, All Other",
        "299021": "Health Information Technologists and Medical Registrars",
        "299091": "Athletic Trainers",
        "299092": "Genetic Counselors",
        "299093": "Surgical Assistants",
        "299099": "Healthcare Practitioners and Technical Workers, All Other",
        "311131": "Nursing Assistants",
        "311132": "Orderlies",
        "311133": "Psychiatric Aides",
        "312011": "Occupational Therapy Assistants",
        "312012": "Occupational Therapy Aides",
        "312021": "Physical Therapist Assistants",
        "312022": "Physical Therapist Aides",
        "319011": "Massage Therapists",
        "319091": "Dental Assistants",
        "319092": "Medical Assistants",
        "319093": "Medical Equipment Preparers",
        "319094": "Medical Transcriptionists",
        "319095": "Pharmacy Aides",
        "319096": "Veterinary Assistants and Laboratory Animal Caretakers",
        "319097": "Phlebotomists",
        "319099": "Healthcare Support Workers, All Other",
        "331011": "First-Line Supervisors of Correctional Officers",
        "331012": "First-Line Supervisors of Police and Detectives",
        "331021": "First-Line Supervisors of Firefighting and Prevention Workers",
        "331091": "First-Line Supervisors of Security Workers",
        "331099": "First-Line Supervisors of Protective Service Workers, All Other",
        "332011": "Firefighters",
        "332021": "Fire Inspectors and Investigators",
        "332022": "Forest Fire Inspectors and Prevention Specialists",
        "333011": "Bailiffs",
        "333012": "Correctional Officers and Jailers",
        "333021": "Detectives and Criminal Investigators",
        "333031": "Fish and Game Wardens",
        "333041": "Parking Enforcement Workers",
        "333051": "Police and Sheriff's Patrol Officers",
        "333052": "Transit and Railroad Police",
        "339011": "Animal Control Workers",
        "339021": "Private Detectives and Investigators",
        "339031": "Gaming Surveillance Officers and Gambling Investigators",
        "339032": "Security Guards",
        "339091": "Crossing Guards and Flaggers",
        "339092": "Lifeguards, Ski Patrol, and Other Recreational Protective Service Workers",
        "339093": "Transportation Security Screeners",
        "339094": "School Bus Monitors",
        "339099": "Protective Service Workers, All Other",
        "351011": "Chefs and Head Cooks",
        "351012": "First-Line Supervisors of Food Preparation and Serving Workers",
        "352011": "Cooks, Fast Food",
        "352012": "Cooks, Institution and Cafeteria",
        "352013": "Cooks, Private Household",
        "352014": "Cooks, Restaurant",
        "352015": "Cooks, Short Order",
        "352019": "Cooks, All Other",
        "352021": "Food Preparation Workers",
        "353011": "Bartenders",
        "353023": "Fast Food and Counter Workers",
        "353031": "Waiters and Waitresses",
        "353041": "Food Servers, Nonrestaurant",
        "359011": "Dining Room and Cafeteria Attendants and Bartender Helpers",
        "359021": "Dishwashers",
        "359031": "Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop",
        "359099": "Food Preparation and Serving Related Workers, All Other",
        "371011": "First-Line Supervisors of Housekeeping and Janitorial Workers",
        "371012": "First-Line Supervisors of Landscaping, Lawn Service, and Groundskeeping Workers",
        "372011": "Janitors and Cleaners, Except Maids and Housekeeping Cleaners",
        "372012": "Maids and Housekeeping Cleaners",
        "372019": "Building Cleaning Workers, All Other",
        "372021": "Pest Control Workers",
        "373011": "Landscaping and Groundskeeping Workers",
        "373012": "Pesticide Handlers, Sprayers, and Applicators, Vegetation",
        "373013": "Tree Trimmers and Pruners",
        "373019": "Grounds Maintenance Workers, All Other",
        "391013": "First-Line Supervisors of Gambling Services Workers",
        "391014": "First-Line Supervisors of Entertainment and Recreation Workers, Except Gambling Services",
        "391022": "First-Line Supervisors of Personal Service Workers",
        "392011": "Animal Trainers",
        "392021": "Animal Caretakers",
        "393011": "Gambling Dealers",
        "393012": "Gambling and Sports Book Writers and Runners",
        "393019": "Gambling Service Workers, All Other",
        "393021": "Motion Picture Projectionists",
        "393031": "Ushers, Lobby Attendants, and Ticket Takers",
        "393091": "Amusement and Recreation Attendants",
        "393092": "Costume Attendants",
        "393093": "Locker Room, Coatroom, and Dressing Room Attendants",
        "393099": "Entertainment Attendants and Related Workers, All Other",
        "394011": "Embalmers",
        "394012": "Crematory Operators",
        "394021": "Funeral Attendants",
        "394031": "Morticians, Undertakers, and Funeral Arrangers",
        "395011": "Barbers",
        "395012": "Hairdressers, Hairstylists, and Cosmetologists",
        "395091": "Makeup Artists, Theatrical and Performance",
        "395092": "Manicurists and Pedicurists",
        "395093": "Shampooers",
        "395094": "Skincare Specialists",
        "396011": "Baggage Porters and Bellhops",
        "396012": "Concierges",
        "399011": "Childcare Workers",
        "399031": "Exercise Trainers and Group Fitness Instructors",
        "399032": "Recreation Workers",
        "399041": "Residential Advisors",
        "399099": "Personal Care and Service Workers, All Other",
        "411011": "First-Line Supervisors of Retail Sales Workers",
        "411012": "First-Line Supervisors of Non-Retail Sales Workers",
        "412011": "Cashiers",
        "412012": "Gambling Change Persons and Booth Cashiers",
        "412021": "Counter and Rental Clerks",
        "412022": "Parts Salespersons",
        "412031": "Retail Salespersons",
        "413011": "Advertising Sales Agents",
        "413021": "Insurance Sales Agents",
        "413031": "Securities, Commodities, and Financial Services Sales Agents",
        "413041": "Travel Agents",
        "413091": "Sales Representatives of Services, Except Advertising, Insurance, Financial Services, and Travel",
        "414011": "Sales Representatives, Wholesale and Manufacturing, Technical and Scientific Products",
        "414012": "Sales Representatives, Wholesale and Manufacturing, Except Technical and Scientific Products",
        "419011": "Demonstrators and Product Promoters",
        "419012": "Models",
        "419021": "Real Estate Brokers",
        "419022": "Real Estate Sales Agents",
        "419031": "Sales Engineers",
        "419041": "Telemarketers",
        "419091": "Door-to-Door Sales Workers, News and Street Vendors, and Related Workers",
        "419099": "Sales and Related Workers, All Other",
        "431011": "First-Line Supervisors of Office and Administrative Support Workers",
        "432011": "Switchboard Operators, Including Answering Service",
        "432021": "Telephone Operators",
        "432099": "Communications Equipment Operators, All Other",
        "433011": "Bill and Account Collectors",
        "433021": "Billing and Posting Clerks",
        "433031": "Bookkeeping, Accounting, and Auditing Clerks",
        "433041": "Gambling Cage Workers",
        "433051": "Payroll and Timekeeping Clerks",
        "433061": "Procurement Clerks",
        "433071": "Tellers",
        "433099": "Financial Clerks, All Other",
        "434011": "Brokerage Clerks",
        "434021": "Correspondence Clerks",
        "434031": "Court, Municipal, and License Clerks",
        "434041": "Credit Authorizers, Checkers, and Clerks",
        "434051": "Customer Service Representatives",
        "434061": "Eligibility Interviewers, Government Programs",
        "434071": "File Clerks",
        "434081": "Hotel, Motel, and Resort Desk Clerks",
        "434111": "Interviewers, Except Eligibility and Loan",
        "434121": "Library Assistants, Clerical",
        "434131": "Loan Interviewers and Clerks",
        "434141": "New Accounts Clerks",
        "434151": "Order Clerks",
        "434161": "Human Resources Assistants, Except Payroll and Timekeeping",
        "434171": "Receptionists and Information Clerks",
        "434181": "Reservation and Transportation Ticket Agents and Travel Clerks",
        "434199": "Information and Record Clerks, All Other",
        "435011": "Cargo and Freight Agents",
        "435021": "Couriers and Messengers",
        "435031": "Public Safety Telecommunicators",
        "435032": "Dispatchers, Except Police, Fire, and Ambulance",
        "435041": "Meter Readers, Utilities",
        "435051": "Postal Service Clerks",
        "435052": "Postal Service Mail Carriers",
        "435053": "Postal Service Mail Sorters, Processors, and Processing Machine Operators",
        "435061": "Production, Planning, and Expediting Clerks",
        "435071": "Shipping, Receiving, and Inventory Clerks",
        "435111": "Weighers, Measurers, Checkers, and Samplers, Recordkeeping",
        "436011": "Executive Secretaries and Executive Administrative Assistants",
        "436012": "Legal Secretaries and Administrative Assistants",
        "436013": "Medical Secretaries and Administrative Assistants",
        "436014": "Secretaries and Administrative Assistants, Except Legal, Medical, and Executive",
        "439021": "Data Entry Keyers",
        "439022": "Word Processors and Typists",
        "439031": "Desktop Publishers",
        "439041": "Insurance Claims and Policy Processing Clerks",
        "439051": "Mail Clerks and Mail Machine Operators, Except Postal Service",
        "439061": "Office Clerks, General",
        "439071": "Office Machine Operators, Except Computer",
        "439081": "Proofreaders and Copy Markers",
        "439111": "Statistical Assistants",
        "439199": "Office and Administrative Support Workers, All Other",
        "451011": "First-Line Supervisors of Farming, Fishing, and Forestry Workers",
        "452011": "Agricultural Inspectors",
        "452021": "Animal Breeders",
        "452041": "Graders and Sorters, Agricultural Products",
        "452091": "Agricultural Equipment Operators",
        "452092": "Farmworkers and Laborers, Crop, Nursery, and Greenhouse",
        "452093": "Farmworkers, Farm, Ranch, and Aquacultural Animals",
        "452099": "Agricultural Workers, All Other",
        "454011": "Forest and Conservation Workers",
        "454021": "Fallers",
        "454022": "Logging Equipment Operators",
        "454023": "Log Graders and Scalers",
        "454029": "Logging Workers, All Other",
        "471011": "First-Line Supervisors of Construction Trades and Extraction Workers",
        "472011": "Boilermakers",
        "472021": "Brickmasons and Blockmasons",
        "472022": "Stonemasons",
        "472031": "Carpenters",
        "472041": "Carpet Installers",
        "472042": "Floor Layers, Except Carpet, Wood, and Hard Tiles",
        "472043": "Floor Sanders and Finishers",
        "472044": "Tile and Stone Setters",
        "472051": "Cement Masons and Concrete Finishers",
        "472053": "Terrazzo Workers and Finishers",
        "472061": "Construction Laborers",
        "472071": "Paving, Surfacing, and Tamping Equipment Operators",
        "472072": "Pile Driver Operators",
        "472073": "Operating Engineers and Other Construction Equipment Operators",
        "472081": "Drywall and Ceiling Tile Installers",
        "472082": "Tapers",
        "472111": "Electricians",
        "472121": "Glaziers",
        "472131": "Insulation Workers, Floor, Ceiling, and Wall",
        "472132": "Insulation Workers, Mechanical",
        "472141": "Painters, Construction and Maintenance",
        "472142": "Paperhangers",
        "472151": "Pipelayers",
        "472152": "Plumbers, Pipefitters, and Steamfitters",
        "472161": "Plasterers and Stucco Masons",
        "472171": "Reinforcing Iron and Rebar Workers",
        "472181": "Roofers",
        "472211": "Sheet Metal Workers",
        "472221": "Structural Iron and Steel Workers",
        "472231": "Solar Photovoltaic Installers",
        "473011": "Helpers--Brickmasons, Blockmasons, Stonemasons, and Tile and Marble Setters",
        "473012": "Helpers--Carpenters",
        "473013": "Helpers--Electricians",
        "473014": "Helpers--Painters, Paperhangers, Plasterers, and Stucco Masons",
        "473015": "Helpers--Pipelayers, Plumbers, Pipefitters, and Steamfitters",
        "473016": "Helpers--Roofers",
        "473019": "Helpers, Construction Trades, All Other",
        "474011": "Construction and Building Inspectors",
        "474021": "Elevator and Escalator Installers and Repairers",
        "474031": "Fence Erectors",
        "474041": "Hazardous Materials Removal Workers",
        "474051": "Highway Maintenance Workers",
        "474061": "Rail-Track Laying and Maintenance Equipment Operators",
        "474071": "Septic Tank Servicers and Sewer Pipe Cleaners",
        "475011": "Derrick Operators, Oil and Gas",
        "475012": "Rotary Drill Operators, Oil and Gas",
        "475013": "Service Unit Operators, Oil and Gas",
        "475022": "Excavating and Loading Machine and Dragline Operators, Surface Mining",
        "475023": "Earth Drillers, Except Oil and Gas",
        "475032": "Explosives Workers, Ordnance Handling Experts, and Blasters",
        "475041": "Continuous Mining Machine Operators",
        "475043": "Roof Bolters, Mining",
        "475044": "Loading and Moving Machine Operators, Underground Mining",
        "475049": "Underground Mining Machine Operators, All Other",
        "475051": "Rock Splitters, Quarry",
        "475071": "Roustabouts, Oil and Gas",
        "475081": "Helpers--Extraction Workers",
        "475099": "Extraction Workers, All Other",
        "491011": "First-Line Supervisors of Mechanics, Installers, and Repairers",
        "492011": "Computer, Automated Teller, and Office Machine Repairers",
        "492021": "Radio, Cellular, and Tower Equipment Installers and Repairers",
        "492022": "Telecommunications Equipment Installers and Repairers, Except Line Installers",
        "492091": "Avionics Technicians",
        "492092": "Electric Motor, Power Tool, and Related Repairers",
        "492093": "Electrical and Electronics Installers and Repairers, Transportation Equipment",
        "492094": "Electrical and Electronics Repairers, Commercial and Industrial Equipment",
        "492095": "Electrical and Electronics Repairers, Powerhouse, Substation, and Relay",
        "492096": "Electronic Equipment Installers and Repairers, Motor Vehicles",
        "492097": "Audiovisual Equipment Installers and Repairers",
        "492098": "Security and Fire Alarm Systems Installers",
        "493011": "Aircraft Mechanics and Service Technicians",
        "493021": "Automotive Body and Related Repairers",
        "493022": "Automotive Glass Installers and Repairers",
        "493023": "Automotive Service Technicians and Mechanics",
        "493031": "Bus and Truck Mechanics and Diesel Engine Specialists",
        "493041": "Farm Equipment Mechanics and Service Technicians",
        "493042": "Mobile Heavy Equipment Mechanics, Except Engines",
        "493043": "Rail Car Repairers",
        "493051": "Motorboat Mechanics and Service Technicians",
        "493052": "Motorcycle Mechanics",
        "493053": "Outdoor Power Equipment and Other Small Engine Mechanics",
        "493091": "Bicycle Repairers",
        "493092": "Recreational Vehicle Service Technicians",
        "493093": "Tire Repairers and Changers",
        "499011": "Mechanical Door Repairers",
        "499012": "Control and Valve Installers and Repairers, Except Mechanical Door",
        "499021": "Heating, Air Conditioning, and Refrigeration Mechanics and Installers",
        "499031": "Home Appliance Repairers",
        "499041": "Industrial Machinery Mechanics",
        "499043": "Maintenance Workers, Machinery",
        "499044": "Millwrights",
        "499045": "Refractory Materials Repairers, Except Brickmasons",
        "499051": "Electrical Power-Line Installers and Repairers",
        "499052": "Telecommunications Line Installers and Repairers",
        "499061": "Camera and Photographic Equipment Repairers",
        "499062": "Medical Equipment Repairers",
        "499063": "Musical Instrument Repairers and Tuners",
        "499064": "Watch and Clock Repairers",
        "499069": "Precision Instrument and Equipment Repairers, All Other",
        "499071": "Maintenance and Repair Workers, General",
        "499081": "Wind Turbine Service Technicians",
        "499091": "Coin, Vending, and Amusement Machine Servicers and Repairers",
        "499092": "Commercial Divers",
        "499094": "Locksmiths and Safe Repairers",
        "499095": "Manufactured Building and Mobile Home Installers",
        "499096": "Riggers",
        "499097": "Signal and Track Switch Repairers",
        "499098": "Helpers--Installation, Maintenance, and Repair Workers",
        "499099": "Installation, Maintenance, and Repair Workers, All Other",
        "511011": "First-Line Supervisors of Production and Operating Workers",
        "512011": "Aircraft Structure, Surfaces, Rigging, and Systems Assemblers",
        "512021": "Coil Winders, Tapers, and Finishers",
        "512028": "Electrical, electronic, and electromechanical assemblers, except coil winders, tapers, and finishers",
        "512031": "Engine and Other Machine Assemblers",
        "512041": "Structural Metal Fabricators and Fitters",
        "512051": "Fiberglass Laminators and Fabricators",
        "512061": "Timing Device Assemblers and Adjusters",
        "513011": "Bakers",
        "513021": "Butchers and Meat Cutters",
        "513022": "Meat, Poultry, and Fish Cutters and Trimmers",
        "513023": "Slaughterers and Meat Packers",
        "513091": "Food and Tobacco Roasting, Baking, and Drying Machine Operators and Tenders",
        "513092": "Food Batchmakers",
        "513093": "Food Cooking Machine Operators and Tenders",
        "513099": "Food Processing Workers, All Other",
        "514021": "Extruding and Drawing Machine Setters, Operators, and Tenders, Metal and Plastic",
        "514022": "Forging Machine Setters, Operators, and Tenders, Metal and Plastic",
        "514023": "Rolling Machine Setters, Operators, and Tenders, Metal and Plastic",
        "514031": "Cutting, Punching, and Press Machine Setters, Operators, and Tenders, Metal and Plastic",
        "514032": "Drilling and Boring Machine Tool Setters, Operators, and Tenders, Metal and Plastic",
        "514033": "Grinding/Lapping/Polishing/Buffing Machine Tool Setters, Operators, and Tenders, Metal and Plastic",
        "514034": "Lathe and Turning Machine Tool Setters, Operators, and Tenders, Metal and Plastic",
        "514035": "Milling and Planing Machine Setters, Operators, and Tenders, Metal and Plastic",
        "514041": "Machinists",
        "514051": "Metal-Refining Furnace Operators and Tenders",
        "514052": "Pourers and Casters, Metal",
        "514061": "Model Makers, Metal and Plastic",
        "514062": "Patternmakers, Metal and Plastic",
        "514071": "Foundry Mold and Coremakers",
        "514072": "Molding, Coremaking, and Casting Machine Setters, Operators, and Tenders, Metal and Plastic",
        "514081": "Multiple Machine Tool Setters, Operators, and Tenders, Metal and Plastic",
        "514111": "Tool and Die Makers",
        "514121": "Welders, Cutters, Solderers, and Brazers",
        "514122": "Welding, Soldering, and Brazing Machine Setters, Operators, and Tenders",
        "514191": "Heat Treating Equipment Setters, Operators, and Tenders, Metal and Plastic",
        "514192": "Layout Workers, Metal and Plastic",
        "514193": "Plating Machine Setters, Operators, and Tenders, Metal and Plastic",
        "514194": "Tool Grinders, Filers, and Sharpeners",
        "514199": "Metal Workers and Plastic Workers, All Other",
        "515111": "Prepress Technicians and Workers",
        "515112": "Printing Press Operators",
        "515113": "Print Binding and Finishing Workers",
        "516011": "Laundry and Dry-Cleaning Workers",
        "516021": "Pressers, Textile, Garment, and Related Materials",
        "516031": "Sewing Machine Operators",
        "516041": "Shoe and Leather Workers and Repairers",
        "516042": "Shoe Machine Operators and Tenders",
        "516051": "Sewers, Hand",
        "516052": "Tailors, Dressmakers, and Custom Sewers",
        "516061": "Textile Bleaching and Dyeing Machine Operators and Tenders",
        "516062": "Textile Cutting Machine Setters, Operators, and Tenders",
        "516063": "Textile Knitting and Weaving Machine Setters, Operators, and Tenders",
        "516064": "Textile Winding, Twisting, and Drawing Out Machine Setters, Operators, and Tenders",
        "516091": "Extruding and Forming Machine Setters, Operators, and Tenders, Synthetic and Glass Fibers",
        "516092": "Fabric and Apparel Patternmakers",
        "516093": "Upholsterers",
        "516099": "Textile, Apparel, and Furnishings Workers, All Other",
        "517011": "Cabinetmakers and Bench Carpenters",
        "517021": "Furniture Finishers",
        "517031": "Model Makers, Wood",
        "517032": "Patternmakers, Wood",
        "517041": "Sawing Machine Setters, Operators, and Tenders, Wood",
        "517042": "Woodworking Machine Setters, Operators, and Tenders, Except Sawing",
        "517099": "Woodworkers, All Other",
        "518011": "Nuclear Power Reactor Operators",
        "518012": "Power Distributors and Dispatchers",
        "518013": "Power Plant Operators",
        "518021": "Stationary Engineers and Boiler Operators",
        "518031": "Water and Wastewater Treatment Plant and System Operators",
        "518091": "Chemical Plant and System Operators",
        "518092": "Gas Plant Operators",
        "518093": "Petroleum Pump System Operators, Refinery Operators, and Gaugers",
        "518099": "Plant and System Operators, All Other",
        "519011": "Chemical Equipment Operators and Tenders",
        "519012": "Separating, Filtering, Clarifying, Precipitating, and Still Machine Setters, Operators, and Tenders",
        "519021": "Crushing, Grinding, and Polishing Machine Setters, Operators, and Tenders",
        "519022": "Grinding and Polishing Workers, Hand",
        "519023": "Mixing and Blending Machine Setters, Operators, and Tenders",
        "519031": "Cutters and Trimmers, Hand",
        "519032": "Cutting and Slicing Machine Setters, Operators, and Tenders",
        "519041": "Extruding, Forming, Pressing, and Compacting Machine Setters, Operators, and Tenders",
        "519051": "Furnace, Kiln, Oven, Drier, and Kettle Operators and Tenders",
        "519061": "Inspectors, Testers, Sorters, Samplers, and Weighers",
        "519071": "Jewelers and Precious Stone and Metal Workers",
        "519081": "Dental Laboratory Technicians",
        "519082": "Medical Appliance Technicians",
        "519083": "Ophthalmic Laboratory Technicians",
        "519111": "Packaging and Filling Machine Operators and Tenders",
        "519123": "Painting, Coating, and Decorating Workers",
        "519124": "Coating, Painting, and Spraying Machine Setters, Operators, and Tenders",
        "519141": "Semiconductor Processing Technicians",
        "519151": "Photographic Process Workers and Processing Machine Operators",
        "519161": "Computer Numerically Controlled Tool Operators",
        "519162": "Computer Numerically Controlled Tool Programmers",
        "519191": "Adhesive Bonding Machine Operators and Tenders",
        "519192": "Cleaning, Washing, and Metal Pickling Equipment Operators and Tenders",
        "519193": "Cooling and Freezing Equipment Operators and Tenders",
        "519194": "Etchers and Engravers",
        "519195": "Molders, Shapers, and Casters, Except Metal and Plastic",
        "519196": "Paper Goods Machine Setters, Operators, and Tenders",
        "519197": "Tire Builders",
        "519198": "Helpers--Production Workers",
        "519199": "Production Workers, All Other",
        "531041": "Aircraft Cargo Handling Supervisors",
        "531047": "First-Line Supervisors of Transportation Workers, Except Aircraft Cargo Handling Supervisors",
        "532011": "Airline Pilots, Copilots, and Flight Engineers",
        "532012": "Commercial Pilots",
        "532021": "Air Traffic Controllers",
        "532022": "Airfield Operations Specialists",
        "532031": "Flight Attendants",
        "533011": "Ambulance Drivers and Attendants, Except Emergency Medical Technicians",
        "533031": "Driver/Sales Workers",
        "533032": "Heavy and Tractor-Trailer Truck Drivers",
        "533033": "Light Truck Drivers",
        "533051": "Bus Drivers, School",
        "533052": "Bus Drivers, Transit and Intercity",
        "533053": "Shuttle Drivers and Chauffeurs",
        "533054": "Taxi Drivers",
        "533099": "Motor Vehicle Operators, All Other",
        "534011": "Locomotive Engineers",
        "534013": "Rail Yard Engineers, Dinkey Operators, and Hostlers",
        "534022": "Railroad Brake, Signal, and Switch Operators and Locomotive Firers",
        "534031": "Railroad Conductors and Yardmasters",
        "534041": "Subway and Streetcar Operators",
        "534099": "Rail Transportation Workers, All Other",
        "535011": "Sailors and Marine Oilers",
        "535021": "Captains, Mates, and Pilots of Water Vessels",
        "535022": "Motorboat Operators",
        "535031": "Ship Engineers",
        "536011": "Bridge and Lock Tenders",
        "536021": "Parking Attendants",
        "536031": "Automotive and Watercraft Service Attendants",
        "536032": "Aircraft Service Attendants",
        "536041": "Traffic Technicians",
        "536051": "Transportation Inspectors",
        "536061": "Passenger Attendants",
        "536099": "Transportation Workers, All Other",
        "537011": "Conveyor Operators and Tenders",
        "537021": "Crane and Tower Operators",
        "537031": "Dredge Operators",
        "537041": "Hoist and Winch Operators",
        "537051": "Industrial Truck and Tractor Operators",
        "537061": "Cleaners of Vehicles and Equipment",
        "537062": "Laborers and Freight, Stock, and Material Movers, Hand",
        "537063": "Machine Feeders and Offbearers",
        "537064": "Packers and Packagers, Hand",
        "537065": "Stockers and Order Fillers",
        "537071": "Gas Compressor and Gas Pumping Station Operators",
        "537072": "Pump Operators, Except Wellhead Pumpers",
        "537073": "Wellhead Pumpers",
        "537081": "Refuse and Recyclable Material Collectors",
        "537121": "Tank Car, Truck, and Ship Loaders",
        "537199": "Material Moving Workers, All Other",
        }
    return soc_dictionary

def search_oews_soc(keyword: List[str]) -> List[Tuple[str, str]]:
    """
    Search for occupations by keyword(s) and return their SOC codes.
    
    Supports flexible multi-word searches and multiple search terms. Results are prioritized by match quality:
    1. Exact word matches (e.g., "manager" → "General and Operations Managers")
    2. All words match (e.g., "software developer" → "Software Developers") 
    3. Partial matches (e.g., "soft" → "Software Developers")
    
    Args:
        keyword (List[str]): Search term(s) to match against occupation titles (case-insensitive).
                            List of strings for multiple searches, or single item list for one search.
    
    Returns:
        List[Tuple[str, str]]: List of (occupation_title, soc_code) tuples matching the search(es)
        
    Examples:
        >>> search_oews_soc(["software"])
        [("Software Developers", "151252"), ("Software Quality Assurance Analysts and Testers", "151253")]
        
        >>> search_oews_soc(["manager", "financial"])
        [("Financial Managers", "113031"), ("General and Operations Managers", "111021"), ...]
        
        >>> search_oews_soc(["computer programmer"])
        [("Computer Programmers", "151251")]
    """
    # keyword is now always a list
    if not keyword:
        return []
    keywords = [k.strip().lower() for k in keyword if k and k.strip()]
    if not keywords:
        return []
    
    soc_data = _get_soc_data()
    all_results = []
    
    # Process each keyword separately
    for search_keyword in keywords:
        # Split the search query into individual terms
        search_terms = re.split(r'\W+', search_keyword)
        search_terms = [term for term in search_terms if term]  # Remove empty strings
        
        if not search_terms:
            continue
        
        # Find matches with different priority levels for this keyword
        exact_matches = []
        all_word_matches = []
        partial_matches = []
        
        for soc_code, occupation_title in soc_data.items():
            title_lower = occupation_title.lower()
            title_words = re.split(r'\W+', title_lower)
            
            # Priority 1: Single term that exactly matches a word in the occupation title
            if len(search_terms) == 1 and search_terms[0] in title_words:
                exact_matches.append((occupation_title, soc_code))
            # Priority 2: All search terms appear as words in the occupation title
            elif len(search_terms) > 1 and all(term in title_words for term in search_terms):
                all_word_matches.append((occupation_title, soc_code))
            # Priority 3: All search terms appear somewhere in the occupation title (substring match)
            elif all(term in title_lower for term in search_terms):
                partial_matches.append((occupation_title, soc_code))
        
        # Combine results for this keyword, prioritizing exact matches
        keyword_results = exact_matches + all_word_matches + partial_matches
        all_results.extend(keyword_results)
    
    # Remove duplicates while preserving order
    seen = set()
    unique_results = []
    for result in all_results:
        if result not in seen:
            seen.add(result)
            unique_results.append(result)
    
    return unique_results

if __name__ == "__main__":
    print(search_oews_soc(["software"]))